"""Signal model: paper-backtest tracker for every NON-REJECTED score.

Independent from Trade (which is the user's real journal). A Signal is
generated by the daily pipeline as a virtual recommendation; the
signal-closer job walks open signals and resolves them to hit_target_1 /
hit_target_2 / hit_stop / expired by replaying PriceDaily bars after the
generation date. Lets us measure if the system actually has edge without
requiring the user to trade every signal.
"""
from __future__ import annotations

from datetime import datetime, date as DateType
from sqlalchemy import (
    String, Float, DateTime, Date, Integer, ForeignKey, Index, JSON,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.core.database import Base


class Signal(Base):
    __tablename__ = "signals"
    __table_args__ = (
        Index("ix_signals_inst_date", "instrument_id", "date_generated"),
        Index("ix_signals_status_date", "status", "date_generated"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    instrument_id: Mapped[int] = mapped_column(Integer, ForeignKey("instruments.id"), index=True)
    date_generated: Mapped[DateType] = mapped_column(Date, index=True)

    tier: Mapped[str | None] = mapped_column(String(8), nullable=True)
    category: Mapped[str | None] = mapped_column(String(32), nullable=True)
    setup_type: Mapped[str | None] = mapped_column(String(32), nullable=True)
    total_score: Mapped[float] = mapped_column(Float, default=0.0)

    entry: Mapped[float | None] = mapped_column(Float, nullable=True)
    stop: Mapped[float | None] = mapped_column(Float, nullable=True)
    target_1: Mapped[float | None] = mapped_column(Float, nullable=True)
    target_2: Mapped[float | None] = mapped_column(Float, nullable=True)

    horizon_days: Mapped[int | None] = mapped_column(Integer, nullable=True)

    factor_scores: Mapped[dict | None] = mapped_column(JSON, nullable=True, default=None)
    multipliers: Mapped[dict | None] = mapped_column(JSON, nullable=True, default=None)

    # Outcome — set by close_open_signals.
    # open / hit_target_1 / hit_target_2 / hit_stop / expired
    status: Mapped[str] = mapped_column(String(16), default="open", index=True)
    exit_price: Mapped[float | None] = mapped_column(Float, nullable=True)
    exit_date: Mapped[DateType | None] = mapped_column(Date, nullable=True)
    days_held: Mapped[int | None] = mapped_column(Integer, nullable=True)
    pnl_pct: Mapped[float | None] = mapped_column(Float, nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
